#pragma once

#define SPI_CR1_CPHA (1 << 0)
#define SPI_CR1_CPOL (1 << 1)
#define SPI_CR1_MSTR (1 << 2)
#define SPI_CR1_BRR_Pos (3)
#define SPI_CR1_BRR_Msk (7U << SPI_CR1_BRR_Pos)
#define SPI_CR1_SPE (1 << 6)
#define SPI_CR1_LSB (1 << 7)
#define SPI_CR1_SSI (1 << 8)
#define SPI_CR1_SSM (1 << 9)
#define SPI_CR1_RX (1 << 10)
#define SPI_CR1_DFF (1 << 11)
#define SPI_CR1_CRC_NEXT (1 << 12)
#define SPI_CR1_CRC_EN (1 << 13)
#define SPI_CR1_BIDIOE (1 << 14)
#define SPI_CR1_BIDIMODE (1 << 15)

#define SPI_CR2_RXDMAEN (1 << 0)
#define SPI_CR2_TXDMAEN (1 << 1)
#define SPI_CR2_SSOE (1 << 2)
#define SPI_CR2_FRF (1 << 4)
#define SPI_CR2_ERRIE (1 << 5)
#define SPI_CR2_RXNEIE (1 << 6)
#define SPI_CR2_TXEIE (1 << 7)

#define SPI_SR_RXNE (1 << 0)
#define SPI_SR_TXE (1 << 1)
#define SPI_SR_CHSIDE (1 << 2)
#define SPI_SR_UDR (1 << 3)
#define SPI_SR_CRC_ERR (1 << 4)
#define SPI_SR_MODF (1 << 5)
#define SPI_SR_OVR (1 << 6)
#define SPI_SR_BSY (1 << 7)
#define SPI_SR_FRE (1 << 8)