#ifndef RCC_BITFIELDS_H
#define RCC_BITFIELDS_H

#define RCC_CFGR_SW_Pos (0)
#define RCC_CFGR_SW_Msk (3U << RCC_CFGR_SW_Pos)
#define RCC_CFGR_SWS_Pos (2)
#define RCC_CFGR_SWS_Msk (3U << RCC_CFGR_SWS_Pos)

#define RCC_CFGR_HPRE_Pos (4)
#define RCC_CFGR_HPRE_Msk (0xFU << RCC_CFGR_HPRE_Pos)
#define RCC_CFGR_PPRE1_Pos (10)
#define RCC_CFGR_PPRE1_Msk (0x7U << RCC_CFGR_PPRE1_Pos)
#define RCC_CFGR_PPRE2_Pos (13)
#define RCC_CFGR_PPRE2_Msk (0x7U << RCC_CFGR_PPRE2_Pos)

#define RCC_AHB1RSTR_GPIOA_RST (1 << 0)
#define RCC_AHB1RSTR_GPIOB_RST (1 << 1)
#define RCC_AHB1RSTR_GPIOC_RST (1 << 2)
#define RCC_AHB1RSTR_GPIOD_RST (1 << 3)
#define RCC_AHB1RSTR_GPIOE_RST (1 << 4)
#define RCC_AHB1RSTR_GPIOH_RST (1 << 7)
#define RCC_AHB1RSTR_CRC_RST (1 << 12)
#define RCC_AHB1RSTR_DMA1_RST (1 << 21)
#define RCC_AHB1RSTR_DMA2_RST (1 << 22)

#define RCC_APB1RSTR_TIM2_RST (1 << 0)
#define RCC_APB1RSTR_TIM3_RST (1 << 1)
#define RCC_APB1RSTR_TIM4_RST (1 << 2)
#define RCC_APB1RSTR_TIM5_RST (1 << 3)
#define RCC_APB1RSTR_WWDG_RST (1 << 11)
#define RCC_APB1RSTR_SPI2_RST (1 << 14)
#define RCC_APB1RSTR_SPI3_RST (1 << 15)
#define RCC_APB1RSTR_USART2_RST (1 << 17)
#define RCC_APB1RSTR_I2C1_RST (1 << 21)
#define RCC_APB1RSTR_I2C2_RST (1 << 22)
#define RCC_APB1RSTR_I2C3_RST (1 << 23)
#define RCC_APB1RSTR_PWR_RST (1 << 28)

#define RCC_APB2RSTR_TIM1_RST (1 << 0)
#define RCC_APB2RSTR_USART1_RST (1 << 4)
#define RCC_APB2RSTR_USART6_RST (1 << 5)
#define RCC_APB2RSTR_ADC1_RST (1 << 8)
#define RCC_APB2RSTR_SDIO_RST (1 << 11)
#define RCC_APB2RSTR_SPI1_RST (1 << 12)
#define RCC_APB2RSTR_SPI4_RST (1 << 13)
#define RCC_APB2RSTR_SYSCFG_RST (1 << 14)
#define RCC_APB2RSTR_TIM9_RST (1 << 16)
#define RCC_APB2RSTR_TIM10_RST (1 << 17)
#define RCC_APB2RSTR_TIM11_RST (1 << 18)

#define RCC_AHB1ENR_GPIOA_EN (1 << 0)
#define RCC_AHB1ENR_GPIOB_EN (1 << 1)
#define RCC_AHB1ENR_GPIOC_EN (1 << 2)
#define RCC_AHB1ENR_GPIOD_EN (1 << 3)
#define RCC_AHB1ENR_GPIOE_EN (1 << 4)
#define RCC_AHB1ENR_GPIOH_EN (1 << 7)
#define RCC_AHB1ENR_CRC_EN (1 << 12)
#define RCC_AHB1ENR_DMA1_EN (1 << 21)
#define RCC_AHB1ENR_DMA2_EN (1 << 22)

#define RCC_AHB2ENR_OTGFS_EN (1 << 7)

#define RCC_APB1ENR_TIM2_EN (1 << 0)
#define RCC_APB1ENR_TIM3_EN (1 << 1)
#define RCC_APB1ENR_TIM4_EN (1 << 2)
#define RCC_APB1ENR_TIM5_EN (1 << 3)
#define RCC_APB1ENR_WWDG_EN (1 << 11)
#define RCC_APB1ENR_SPI2_EN (1 << 14)
#define RCC_APB1ENR_SPI3_EN (1 << 15)
#define RCC_APB1ENR_USART2_EN (1 << 17)
#define RCC_APB1ENR_I2C1_EN (1 << 21)
#define RCC_APB1ENR_I2C2_EN (1 << 22)
#define RCC_APB1ENR_I2C3_EN (1 << 23)
#define RCC_APB1ENR_PWR_EN (1 << 28)

#define RCC_APB2ENR_TIM1_EN (1 << 0)
#define RCC_APB2ENR_USART1_EN (1 << 4)
#define RCC_APB2ENR_USART6_EN (1 << 5)
#define RCC_APB2ENR_ADC1_EN (1 << 8)
#define RCC_APB2ENR_SDIO_EN (1 << 11)
#define RCC_APB2ENR_SPI1_EN (1 << 12)
#define RCC_APB2ENR_SPI4_EN (1 << 13)
#define RCC_APB2ENR_SYSCFG_EN (1 << 14)
#define RCC_APB2ENR_TIM9_EN (1 << 16)
#define RCC_APB2ENR_TIM10_EN (1 << 17)
#define RCC_APB2ENR_TIM11_EN (1 << 18)

#define RCC_CR_HSION (1 << 0)
#define RCC_CR_HSIRDY (1 << 1)
#define RCC_CR_HSITRIM (1 << 3)
#define RCC_CR_HSICAL (1 << 8)
#define RCC_CR_HSEON (1 << 16)
#define RCC_CR_HSERDY (1 << 17)
#define RCC_CR_HSEBYP (1 << 18)
#define RCC_CR_CSSON (1 << 19)
#define RCC_CR_PLLON (1 << 24)
#define RCC_CR_PLLRDY (1 << 25)
#define RCC_CR_PLLI2SON (1 << 24)
#define RCC_CR_PLLI2SRDY (1 << 24)

#define RCC_PLLCFGR_PLLM_Pos (0)
#define RCC_PLLCFGR_PLLN_Pos (6)
#define RCC_PLLCFGR_PLLP_Pos (16)
#define RCC_PLLCFGR_PLLQ_Pos (24)
#define RCC_PLLCFGR_PLLSRC_Pos (22)

#define RCC_PLLCFGR_PLLM_Msk (0x3FU << RCC_PLLCFGR_PLLM_Pos)
#define RCC_PLLCFGR_PLLN_Msk (0x1FFU << RCC_PLLCFGR_PLLN_Pos)
#define RCC_PLLCFGR_PLLP_Msk (0x3U << RCC_PLLCFGR_PLLP_Pos)

#define RCC_BDCR_LSEON (1 << 0)
#define RCC_BDCR_LSERDY_Msk (1 << 1)
#define RCC_BDCR_LSEBYP (1 << 2)
#define RCC_BDCR_RTCSEL_Pos 8
#define RCC_BDCR_RTCSEL_Msk (0x3U << RCC_BDCR_RTCSEL_Pos)
#define RCC_BDCR_RTCSEL_LSE (1 << RCC_BDCR_RTCSEL_Pos)
#define RCC_BDCR_RTCEN (1 << 15)
#define RCC_BDCR_BDRST (1 << 16)

#endif