#ifndef USBOTG_BITFIELDS_H
#define USBOTG_BITFIELDS_H

#define USB_OTG_FS_GRSTCTL_CSRST (1 << 0)
#define USB_OTG_FS_GRSTCTL_HSRST (1 << 1)
#define USB_OTG_FS_GRSTCTL_FCRST (1 << 2)
#define USB_OTG_FS_GRSTCTL_RXFFLSH (1 << 4)
#define USB_OTG_FS_GRSTCTL_TXFFLSH (1 << 5)
#define USB_OTG_FS_GRSTCTL_TXFNUM_Pos 6
#define USB_OTG_FS_GRSTCTL_AHBIDL_Pos 31

#define USB_OTG_FS_GUSBCFG_TOCAL_Pos 0
#define USB_OTG_FS_GUSBCFG_PHYSEL_Pos 6
#define USB_OTG_FS_GUSBCFG_SRPCAP (1 << 8)
#define USB_OTG_FS_GUSBCFG_HNPCAP (1 << 9)
#define USB_OTG_FS_GUSBCFG_TRDT (1 << 10)
#define USB_OTG_FS_GUSBCFG_FHMOD (1 << 29)
#define USB_OTG_FS_GUSBCFG_FDMOD (1 << 30)
#define USB_OTG_FS_GUSBCFG_CTXPKT (1 << 31)

#define OTG_FS_DCTL_RWUSIG (1 << 0)
#define OTG_FS_DCTL_SDIS (1 << 1)
#define OTG_FS_DCTL_GINSTS (1 << 2)
#define OTG_FS_DCTL_GONSTS (1 << 3)
#define OTG_FS_DCTL_TCTL (1 << 4)
#define OTG_FS_DCTL_SGINAK (1 << 7)
#define OTG_FS_DCTL_CGINAK (1 << 8)
#define OTG_FS_DCTL_SGONAK (1 << 9)
#define OTG_FS_DCTL_CGONAK (1 << 10)
#define OTG_FS_DCTL_POPRGDNE (1 << 11)

#define USB_OTG_FS_PCGCCTL_STPPCLK (1 << 0)
#define USB_OTG_FS_PCGCCTL_GATEHCLK (1 << 1)
#define USB_OTG_FS_PCGCCTL_PHYSUSP (1 << 4)

#endif